# .github/workflows/gh-pages.yml

name: Publicar Jekyll en GitHub Pages

on:
  push:
    branches:
      - main # O la rama que uses para tu sitio

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 1️⃣ Hacer checkout del repositorio
        uses: actions/checkout@v3

      # (Opcional) Si necesitas instalar gemas de algún Gemfile,
      # puedes descomentar esto y usar una versión concreta de Ruby:
      #
      # - name: 2️⃣ Instalar Ruby y Bundler
      #   uses: ruby/setup-ruby@v1
      #   with:
      #     ruby-version: '3.2.2'    # Pincha aquí una versión válida
      #     bundler-cache: true

      - name: 3️⃣ Build de Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: "." # Lee tus fuentes desde la raíz
          destination: "docs" # Genera todo en /docs

      - name: 4️⃣ Verificar contenido de docs/
        run: |
          echo "=== CONTENIDO DE docs/ tras el build ==="
          ls -R docs/
